version: "3.9"

services:
  app:
    build: .
    container_name: rover_app
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
      - redis
      - rabbitmq
      - mqtt
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:17
    container_name: rover_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresPWD@123
      POSTGRES_DB: roverdrone
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: rover_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rover_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" # web management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mqtt:
    image: eclipse-mosquitto:2
    container_name: rover_mqtt
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto_config:/mosquitto/config

volumes:
  db_data:
  redis_data:
  rabbitmq_data:
  mosquitto_data:
  mosquitto_config:
